[project]
name = "miette-py"
requires-python = ">=3.10,<4"
classifiers = ["Private :: Do Not Upload"]
dynamic = ["version"]

[build-system]
requires = ["maturin>=1.7.7,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]